### PR TITLE
Preparing for publishing fjage.js onto npm

### PR DESCRIPTION
**Pull request by notthetup**
npm is the nodejs/javascript package manager. The code change in this PR prepares the file structure for this. 

We will create a `dist` directory, generate a minified js file, and push that those two to npm.

We will start doing this from the next fjage release onwards.

### CODE REVIEW

**Review by mchitre — APPROVED** [review]
I assume it works with `nodejs` now?

**Comment by mchitre** [comment]
Why did the build failed? The logs are almost impossible to track down, as gradle is in debug mode and generating way too much logs!

**Comment by notthetup** [comment]
It won't really work with modems yet. Mainly because Nodejs API for doing WebSockets isn't the same as browser's API 😭

Also nodejs doesn't support Javascript modules yet. 🤷🏽‍♂️

**Comment by notthetup** [comment]
It passed when I reran. The error seemed related to gradle and java running on Github actions.

Although I did notice this warning about `fjage.c`. I'll raise a separate issue.

```

02:51:42.624 [DEBUG] [TestEventLogger]      err = In file included from /usr/include/x86_64-linux-gnu/bits/libc-header-start.h:33:0,
02:51:42.625 [DEBUG] [TestEventLogger]                      from /usr/include/stdio.h:27,
02:51:42.625 [DEBUG] [TestEventLogger]                      from test_fjage.c:25:
02:51:42.625 [DEBUG] [TestEventLogger]     /usr/include/features.h:184:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
02:51:42.625 [DEBUG] [TestEventLogger]      # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
02:51:42.625 [DEBUG] [TestEventLogger]        ^~~~~~~
02:51:42.625 [DEBUG] [TestEventLogger]     In file included from /usr/include/x86_64-linux-gnu/bits/libc-header-start.h:33:0,
02:51:42.625 [DEBUG] [TestEventLogger]                      from /usr/include/stdio.h:27,
02:51:42.625 [DEBUG] [TestEventLogger]                      from fjage.c:11:
02:51:42.625 [DEBUG] [TestEventLogger]     /usr/include/features.h:184:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
02:51:42.625 [DEBUG] [TestEventLogger]      # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
02:51:42.625 [DEBUG] [TestEventLogger]        ^~~~~~~
02:51:42.625 [DEBUG] [TestEventLogger]     In file included from /usr/include/x86_64-linux-gnu/bits/libc-header-start.h:33:0,
02:51:42.625 [DEBUG] [TestEventLogger]                      from /usr/include/stdio.h:27,
02:51:42.625 [DEBUG] [TestEventLogger]                      from encode.c:8:
02:51:42.625 [DEBUG] [TestEventLogger]     /usr/include/features.h:184:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
02:51:42.626 [DEBUG] [TestEventLogger]      # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
02:51:42.626 [DEBUG] [TestEventLogger]        ^~~~~~~
02:51:42.626 [DEBUG] [TestEventLogger]     In file included from /usr/include/x86_64-linux-gnu/bits/libc-header-start.h:33:0,
02:51:42.626 [DEBUG] [TestEventLogger]                      from /usr/include/stdio.h:27,
02:51:42.630 [DEBUG] [TestEventLogger]                      from decode.c:8:
02:51:42.630 [DEBUG] [TestEventLogger]     /usr/include/features.h:184:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
02:51:42.630 [DEBUG] [TestEventLogger]      # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
02:51:42.630 [DEBUG] [TestEventLogger]        ^~~~~~~
```

**Review by AnneThKu — APPROVED** [review]

**Pull request merged**
