### PR TITLE
fix(fjagejs): aligning to fjage behaviour by removing rejecting in ca…

### PR DESCRIPTION
**Pull request by notthetup**
…ses of timeout errors and resolving with a null object instead

### CODE REVIEW

**Comment by mchitre** [comment]
Sounds fine to me

**Comment by mchitre** [comment]
What is the impact on all web pages that currently use fjage.js?

**Comment by notthetup** [comment]
It shouldn't be much. Mainly the change would have to be updating `try..catch` blocks to null checks. But I believe we already have null checks for the values returning by Promises. Will verify.

**Comment by notthetup** [comment]
I take that back, we will need some changes to the WebUI. There is a lot of code of the following format.

```
gw.request(req).then((rsp) => {
      nodeAddr.innerHTML = rsp.value;
    }).catch((ex) => {
      console.warn('Couldn\'t get Node Address' + ex);
      nodeAddr.innerHTML = '';
    });
```

It will have to be changed to 

```
gw.request(req).then( rsp => {
  if (!rsp) console.warn('Couldn\'t get Node Address' + ex);
  nodeAddr.innerHTML = rsp ? rsp.value : '';
})
```

**Comment by mchitre** [comment]
Better to put in 1.7 then, since it breaks backward compatibility?

**Comment by mchitre** [comment]
Ready to merge?

**Comment by notthetup** [comment]
Yup!

**Pull request merged**
