### PR TITLE
Shell scrollbar style

### PR DESCRIPTION
**Pull request by jjophi**
Scrollbar style updated.

The original ones looked like this.

Screenshot 2024-03-15 at 2 57 48 PM
Screenshot 2024-03-15 at 2 57 55 PM

### CODE REVIEW

**Comment by notthetup** [comment]
Screenshot 2024-03-15 at 2 50 50 PM
Screenshot 2024-03-15 at 2 50 55 PM

**Comment by notthetup** [comment]
Adding @manuignatius for reviewing the look and feel.

**Comment by manuignatius** [comment]
> Updated ones look like this.
> 
> Screenshot 2024-03-15 at 2 50 50 PM Screenshot 2024-03-15 at 2 50 55 PM

This styles looks good

**Comment by notthetup** [comment]
Wondering about the little space next to the scroll bar. If there's someway we can remove it. Let me investigate.
Screenshot 2024-03-15 at 3 33 09 PM

**Comment by notthetup** [comment]
OK. That seems to be coming from the container UI. So all good here.


Screenshot 2024-03-15 at 3 38 21 PM


Screenshot 2024-03-15 at 3 38 00 PM

**Review by manuignatius — APPROVED** [review]

**Pull request merged**
