### PR TITLE
Lambda support for behaviors

### PR DESCRIPTION
**Pull request by ngyewch**
# Sample usage
TestAgent.java
```
import org.arl.fjage.*;

public class TestAgent extends Agent {

    @Override
    public void init() {
        add(OneShotBehavior.create(() -> System.out.println("Hello, world!")));

        add(PoissonBehavior.create(5000, () -> System.out.println("Hello, world every 5s (Poisson)!")));

        add(TickerBehavior.create(5000, () -> System.out.println("Hello, world every 5s!")));

        add(WakerBehavior.create(5000, () -> System.out.println("Hello, world after 5s!")));
    }
}
```

### CODE REVIEW

**Comment by mchitre** [comment]
To be consistent with the rest of the API, can we do this style?

```
add(new OneShotBehavior(() -> System.out.println("Hello, world!")));
add(new TickerBehavior(5000, () -> System.out.println("Hello, world every 5s!")));
```

**Comment by ngyewch** [comment]
That works too. I'll redo the pull request.

**Comment by mchitre** [comment]
Cool! But might need your help to resolve merge conflicts 😬, and I'll merge!

**Comment by ngyewch** [comment]
@mchitre After running a simple test, it seems that adding the new constructors will cause a conflict with the Groovy extensions. Let's not merge this just yet.

```
groovy.lang.GroovyRuntimeException: Cannot add new constructor for arguments [[class groovy.lang.Closure]]. It already exists!
        at groovy.lang.ExpandoMetaClass$ExpandoMetaConstructor.leftShift(ExpandoMetaClass.java:695)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:70)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at org.arl.fjage.GroovyExtensions.enable(GroovyExtensions.groovy:33)
        at org.arl.fjage.shell.GroovyBoot.main(GroovyBoot.java:49)
```

**Comment by mchitre** [comment]
Oh OK. Maybe just removing the Groovy extension constructors might do the trick? The closures will be treated as Java lambdas? Might need to experiment a bit to check...

**Comment by mchitre** [comment]
@ngyewch shall we include this in fjåge 1.8? If so, we may need to work out the issue with the Groovy API clash.

**Comment by ngyewch** [comment]
Hmm, yes lemme bump this up on my priority list.

**Comment by ngyewch** [comment]
@mchitre Turns out that the Groovy extensions for those constructors are no longer necessary. Pretty simple fix.

Tests: https://github.com/ngyewch/fjage/blob/lambda-support-test/README-lambda-support.md

**Pull request merged**
